name: Update filters

on:
  push:
    branches:
      - master

concurrency:
  group: update-filters
  cancel-in-progress: true

jobs:
  update-filters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: generator
        run: npm install

      - name: Generate filters
        working-directory: generator
        run: npm run build:filter

      - name: Compute current MD5 of modes configuration
        id: compute-md5
        run: |
          cat generator/configuration/modes.json generator/configuration/globals.json generator/configuration/themes.json | md5sum > .github/infographic-md5-new
          if [ -f .github/infographic-md5 ]; then
            if cmp --silent .github/infographic-md5 .github/infographic-md5-new; then
              echo "No changes in configuration."
              echo "changed=false" >> $GITHUB_ENV
            else
              echo "Configuration changed, proceeding with table generation."
              echo "changed=true" >> $GITHUB_ENV
            fi
          else
            echo "No previous MD5 file found, assuming configuration changed."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Install chromium
        if: env.changed == 'true'
        working-directory: generator
        run: npx playwright install --with-deps

      - name: Generate table image
        if: env.changed == 'true'
        working-directory: generator
        run: npm run build:infographic

      - name: Update current MD5 file of modes configuration
        if: env.changed == 'true'
        run: mv .github/infographic-md5-new .github/infographic-md5

      - name: Commit and push updated files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add *.filter
          git add .github/infographic-md5
          git add .github/infographic.png

          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping commit step.";
            exit 0;
          fi

          git commit -m "Filters updated after merge"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
